name: "Lint & Formatting (CI)"

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Deno 1.35
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.35

      - name: Deno Linter
        run: deno lint

      - name: Deno Formatter
        run: deno fmt --no-semicolons --single-quote --check
