name: Unit testing (CI)

on:
  workflow_call:

jobs:
  test:
    env:
      OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
      OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Deno 1.35
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.35

      - name: Print
        run : |
          echo $OPENAI_KEY
          echo $OPENAI_MODEL

      - name: Run tests
        run: deno test tests/ --allow-read --allow-env --allow-net
