name: Unit testing (CI)

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Deno 1.35
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.35

      - name: Run tests
        run: OPENAI_KEY=${{ secrets.OPENAI_KEY }} OPENAI_MODEL=${{ secrets.OPENAI_MODEL }} deno test tests/ --allow-read --allow-env --allow-net
