name: Pull Request to main

on:
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
  code_quality:
    uses: ./.github/workflows/_lint.yml
  test:
    uses: ./.github/workflows/_test.yml
    secrets: inherit 
