name: Pull Request to main

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  code_quality:
    name: Call linter
    uses: ./.github/worflows/_lint.yml
  test:
    name: Call unit tests
    uses: ./.github/workflows/_test.yml
