name: Release to Deno Deploy (CD)

on:
  push:
    branches:
      - main

jobs:
  lint_test:
    uses: ./.github/worflows/pr_to_main.yml
  release:
    needs: link_test
    uses: ./.github/workflows/_deploy.yml
