name: Release to Deno Deploy (CD)

on:
  push:
    branches:
      - main

jobs:
  lint_test:
    uses: ./.github/workflows/pr-to-main.yml
    
  release:
    needs: lint_test
    uses: ./.github/workflows/_deploy.yml
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository
