name: Release to Deno Deploy (CD)

on:
  push:
    branches:
      - main

jobs:
  lint_test:
    name: Call Lint and Tests
    uses: ./.github/workflows/pr_to_main.yml
  release:
    name: Call Deployment
    needs: lint_test
    uses: ./.github/workflows/_deploy.yml
